### PR TITLE
State when paused

### LINKED ISSUE #234: Guest state after skip while paused
When a song is skipped while paused, the guest playbar and now playing icon do not have the correct state.

The guest playbar will continue to show the last song that was played, and the now playing icon disappears.

To replicate:
- connect 2 phones
- add some songs to the library
- press play
- press pause
- press skip

### LINKED ISSUE #244: Skipping song when paused does not update the current song in the player
Steps to reproduce:

1) Connect two phones and add three songs to the playlist from any device.
2) Play the first song and pause before it ends (from any device).
3) Skip to the third song (from any device).
4) Press play (from any device).

Expected: The third song should play.

Actual: The first song resumes playing.

This resolves if either host or guest skips while the song is playing.

### LINKED ISSUE #248: Removing currently playing song when paused will not change the song when played
Observed during test 19a.  Pressing skip when playing fixes the state and resolves the issue.

### PR DESCRIPTION
**Pull request by theJenix**
Fixed issues with skipping/removing when paused by ensuring that any "set next song call" effectively will cause the player to play from the beginning of whatever song is set.

Fixed issue with synchronization between host and guest by sending playStatusMessage when host sets a new song.

Fixes #234
Fixes #244
Fixes #248

### CODE REVIEW

File: SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java [hunk 1]
```diff
@@ -580,6 +584,11 @@ public void pause() {
     }
 
     public void skip() {
+    	//TODO: I'm not sure I like this...the player ends up sending the same intent
+    	// for when a song is "finished", which is handled above, which calls setNextSong
+    	//...this presents an unobvious execution path, and conflates the acts of
+    	// skipping to the next song, and finishing playing the next song, and has
+    	// led to some unobvious bugs -- Jesse 08/04/13
```
Comment (dgreenhalgh) [inline SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java:591]: You say "has led to unobvious bugs" - could this be a problem child for the future?

**Comment by dgreenhalgh** [comment]
I like this. @reidbaker, what do you think?

File: SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java (hunk 1 above)
Comment (theJenix) [inline SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java:591]: This round about chain of events kind of caused the current bug being fixed (in some ways), and made it really hard to construct an easy fix (hence the amount of change).  I think it's good for now, but I'll add a "refactor" issue to take another look at this whole thing.

**Comment by reidbaker** [comment]
yeah I am pulling this in

File: SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java (hunk 1 above)
Comment (dgreenhalgh) [inline SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java:591]: Yeah, this may be something we want to look into between beta and 1.0
