### PR TITLE
Fragment title fix

### LINKED ISSUE #221: Fragment titles don't update when accessed through menu button
Repro:
Open any fragment (tested with About)
Notice: Title changes to About
Press the icon in the top left to open the drawer
Notice: Title changes to Soundstream
Use the icon again to close the drawer and return to the fragment
Notice: Title doesn't change back to fragment title.

Test Execution: http://wrobellion.com:8080/test/com.lastcrusade.soundstream.ete.tests.AboutFragmentTest/testTitle.html

### PR DESCRIPTION
**Pull request by ejohnson44**
Fixes #221

When toggling the menu with the home button, the fragment titles now update correctly.

### CODE REVIEW

File: SoundStream/src/com/lastcrusade/soundstream/CoreActivity.java [hunk 1]
```diff
@@ -178,6 +178,11 @@ public boolean onOptionsItemSelected(MenuItem item) {
             if(getSlidingMenu().isMenuShowing() && menu.isAdded()){
                 setTitle(((ITitleable)menu).getTitle());
             }
+            else{
```
Comment (theJenix) [inline SoundStream/src/com/lastcrusade/soundstream/CoreActivity.java]: Suggest you rewrite this to hold the ITitleable in a local variable, and call setTitle once.  This will simplify the code.

**Comment by reidbaker** [comment]
If @theJenix likes it its good with me
