### PR TITLE
menu is no longer accessible from the connect fragment

### LINKED ISSUE #196: Able to access drawer from home screen after disconnecting/disbanding network
To reproduce:
1. Open a clean copy of the app, click "Create".
2. Open the network fragment and click "Disconnect".
3. Return to the home screen, and click the icon in the top left corner.

Observe that the drawer opens vs expected behavior of prohibiting user from clicking that button from the screen.

### PR DESCRIPTION
**Pull request by ejohnson44**
fixes #196

### CODE REVIEW

File: SoundStream/src/com/lastcrusade/soundstream/CoreActivity.java [hunk 1]
```diff
@@ -94,20 +95,13 @@ public void onCreate(Bundle savedInstanceState){
...
-            hidePlaybar();
-        }
-        else{
-            //if we're not entering for the first time, we want to make sure that 
-            //we still have access to the sliding menu
-            enableSlidingMenu();
-            showPlaybar();
         }
-
+
```
Comment (reidbaker) [inline SoundStream/src/com/lastcrusade/soundstream/CoreActivity.java]: If you get a chance kill this whitespace later

File: SoundStream/src/com/lastcrusade/soundstream/CoreActivity.java [hunk 2]
```diff
@@ -176,7 +170,8 @@ public void onBackPressed() {
     
     public boolean onOptionsItemSelected(MenuItem item) {
         // home references the app icon
-        if (item.getItemId() == android.R.id.home) {
+        Fragment currentFragment = getSupportFragmentManager().findFragmentByTag("currentContent");
```
Comment (reidbaker) [inline SoundStream/src/com/lastcrusade/soundstream/CoreActivity.java]: Can we put the string "currentContent" one place and reference it here and in transitions

**Comment by reidbaker** [comment]
:thumbsup:
