### PR TITLE
bump song guest fix

### LINKED ISSUE #167: Bump Song Jumps (Guest)
When bumping a song on the guest, the song jumps to the top and then settles back in the right place instead of going there immediately

### PR DESCRIPTION
**Pull request by ejohnson44**
moved the call to bump and remove songs to inside the local player checks

fixes #167

### CODE REVIEW

**Comment by dgreenhalgh** [comment]
:+1:

File: SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java [hunk 1]
```diff
@@ -511,17 +512,17 @@ public void addSong(PlaylistEntry entry) {
...
-        if (isLocalPlayer) {
-            mDataManager.addToLoadQueue(entry);
-        }
-        new LocalBroadcastIntent(ACTION_SONG_ADDED)
-            .putExtra(EXTRA_SONG, entry)
-            .send(this);
-        // send an intent to the fragments that the playlist is updated
-        new LocalBroadcastIntent(ACTION_PLAYLIST_UPDATED).send(this);
-
         if (isLocalPlayer) {
```
Comment (reidbaker) [inline SoundStream/src/com/lastcrusade/soundstream/service/PlaylistService.java:556]: I dont think this is right. You have if isLocalPlayer under a check for isLocalPlayer.
